var nm1 = ["Aegis","Aeon","Aeris","Babylon","Aeternitas","Aether","Alliance","Alpha","Amazone","Ancestor","Anemone","Angel","Anomaly","Apollo","Arcadia","Arcadis","Arch","Architect","Ark","Artemis","Asphodel","Asteria","Astraeus","Athena","Atlas","Atmos","Aura","Aurora","Awe","Azura","Azure","Baldur","Beacon","Blue Moon","Borealis","Burrow","Caelestis","Canaan","Century","Chrono","Chronos","Crescent","Curator","Curiosity","Data","Dawn","Daydream","Demeter","Dogma","Dream","Dune","Ecstasis","Eir","Elyse","Elysium","Empyrea","Ender","Enigma","Eos","Epiphany","Epitome","Erebus","Escort","Eternis","Eternity","Exposure","Fable","Father","Fauna","Felicity","Flora","Fortuna","Frontier","Gaia","Galaxy","Genesis","Genius","Glory","Guardian","Halo","Heirloom","Helios","Hemera","Hera","Heritage","Hermes","Horus","Hymn","Hyperion","Hypnos","Ignis","Illume","Inception","Infinity","Iris","Janus","Juno","Legacy","Liberty","Lore","Lucent","Lumina","Luminous","Luna","Lunis","Magni","Mammoth","Mani","Marvel","Memento","Minerva","Miracle","Mother","Muse","Mystery","Mythos","Nebula","Nemesis","Nemo","Neo","Nero","Nimbus","Nott","Nova","Novis","Nox","Nyx","Odyssey","Olympus","Omega","Oracle","Orbital","Origin","Orphan","Osiris","Outlander","Parable","Paradox","Paragon","Pedigree","Phantasm","Phantom","Phenomenon","Phoenix","Pilgrim","Pioneer","Prism","Prodigy","Prometheus","Prophecy","Proto","Radiance","Rebus","Relic","Revelation","Reverie","Rogue","Rune","Saga","Sancus","Scout","Selene","Serenity","Settler","Shangris","Shepherd","Shu","Sol","Solas","Spectacle","Specter","Spectrum","Spire","Symbolica","Tartarus","Terminus","Terra","Terran","Terraria","Themis","Tiberius","Titan","Titanus","Torus","Tranquility","Trivia","Utopis","Valhalla","Vanguard","Vanquish","Vesta","Vestige","Victoria","Virtue","Visage","Voyage","Vulcan","Warden","Yggdrasil","Zeus","Zion"];
var nm2 = ["","Colony","Station","Colony","Station","Base","Terminal",""];
var nm3 = ["","Colonie","Colonie","Station","Station","Base","Terminus","Terminal"];
var nm4 = ["Éclat","Égide","Élysée","Énigme","Épiphanie","Éternité","Éther","Étranger","Aeon","Aeris","Aeternitas","Aiguille","Alliance","Alpha","Amazone","Ange","Ange Gardien","Anomalie","Apollon","Arcadia","Arcadis","Arche","Architecte","Artemis","Aspodèle","Astérion","Astraeus","Athena","Atlas","Atmos","Aube","Aura","Aurore","Avant-Garde","Avantage","Azura","Azure","Babylone","Baldur","Balise","Berger","Boréales","Céleste","Canaan","Cendre","Chance","Chronos","Clarté","Colonisateur","Connaissance","Coquin","Crainte","Curateur","Curiosité","Début","Découverte","Destin","Dogme","Données","Dune","Empyrée","Erebus","Escorte","Félicité","Fable","Fantôme","Fantasme","Faune","Flèche","Flore","Fortune","Frontière","Génie","Gaia","Galaxie","Gamme","Gardien","Genèse","Gloire","Hélios","Héraut","Héritage","Halo","Hera","Hermès","Horus","Hymne","Hypérion","Hypnose","Illume","Infinité","Insigne","Iris","Janus","Juno","Légende","Liberté","Lumen","Luminosité","Luna","Lune","Lunisolar","Mère","Mémento","Mérite","Magnificence","Magnus","Mammouth","Merveille","Minerva","Miracle","Monstre","Muse","Mystère","Mythe","Nébuleuse","Némésis","Néo","Naissance","Nemo","Nero","Nimbe","Nimbus","Nova","Novis","Nyx","Odyssée","Olympe","Oméga","Oracle","Orbite","Origine","Orphelin","Osiris","Pâtre","Pèlerin","Père","Parabole","Paradoxe","Parangon","Pasteur","Patrimoine","Pedigree","Phénix","Phénomène","Phare","Pionneer","Prisme","Prodige","Prométhée","Prophétie","Protecteur","Proto","Provenance","Rébus","Révélation","Révelátion","Rêvasserie","Rêve","Rêverie","Rayonnement","Reconnaissance","Refuge","Relique","Rune","Sérénité","Saga","Sancus","Scout","Selene","Siècle","Sion","Sol","Solas","Soleil","Songerie","Spectacle","Spectre","Splendeur","Symbole","Terra","Terrarium","Terre","Themis","Tibère","Titan","Torus","Tranquillité","Triomphe","Trivia","Utopie","Valhalla","Vertu","Vesta","Vestale","Vestige","Victoire","Victoria","Visage","Voyage","Voyageur","Vulcain","Yggdrasil","Zeus"];

function nameGen(type){
	var tp = type;

	for (i = 0; i < count; i++){
		if(tp === 1){
			rnd =  Math.random() * nm3.length | 0;
			rnd2 = Math.random() * nm4.length | 0;
			names = nm3[rnd] + " " + nm4[rnd2];
		}else{
			rnd =  Math.random() * nm1.length | 0;
			rnd2 = Math.random() * nm2.length | 0;
			names = nm1[rnd] + " " + nm2[rnd2];
		}
		print(names);
	}
}